/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [ProductKey]
      ,[OrderDateKey]
      ,[DueDateKey]
      ,[ShipDateKey]
      ,[CustomerKey]
     -- ,[PromotionKey]
     -- ,[CurrencyKey]
      --,[SalesTerritoryKey]
      ,[SalesOrderNumber]
    --  ,[SalesOrderLineNumber]
    ---  ,[RevisionNumber]
     --- ,[OrderQuantity]
     -- ,[UnitPrice]
      --,[ExtendedAmount]
   --   ,[UnitPriceDiscountPct]
     -- ,[DiscountAmount]
     -- ,[ProductStandardCost]
     -- ,[TotalProductCost]
      ,[SalesAmount]
    --  ,[TaxAmt]
    --  ,[Freight]
     -- ,[CarrierTrackingNumber]
    --  ,[CustomerPONumber]
    --  ,[OrderDate]
   --   ,[DueDate]
      --,[ShipDate]
	
  FROM [AdventureWorksDW2017].[dbo].[FactInternetSales]
   where left (orderdatekey,4) >= year (getdate()) -2 -- ensure we bring only two years
   order by ProductKey asc